### PR TITLE
- Already incorporated in ADDITIONAL_BACKENDS - Add extra backend settings

### PR DESCRIPTION
**Pull request by Sikian**
This will allow haproxy to be configured with additional backend settings without strict constraints on linked servers (f.e. when wanting to forward to external servers)

I know this might not be the best solution to this, but as I needed a solution for this issue I wanted to share mine.

### CODE REVIEW

**Comment by fabn** [comment]
This could be very useful in some cases. Any review?

**Comment by tifayuki** [comment]
@fabn 
I think there is an envvar `ADDITIONAL_BACKENDS` doing the same job:
https://github.com/docker/dockercloud-haproxy#global-and-default-settings-of-haproxy

**Comment by fabn** [comment]
@tifayuki I thought that it just configure linked backends, I'll try that. Thanks.

**Comment by fabn** [comment]
@tifayuki I'm trying to experiment with `ADDITIONAL_BACKENDS` env variable, but I'm not able to do anything useful. I do not "speak" python but I think that parse occurs in [this code](https://github.com/docker/dockercloud-haproxy/blob/b8810153dc915181fd2b8c30856bdacbff65acfc/haproxy/config.py#L36-L49)

It seems that the code reads env variables named `ADDITIONAL_BACKEND_XXX` and not `ADDITIONAL_BACKENDS`.

Since I do not understand rest of code, could you please provide a concrete example of using those variables? Something like how to create a backend named foo that forward to host foo.example.com:1234 with some options. I.e. how to create this backend in haproxy syntax

```
backend foo
  server some-server foo.example.com:1234 check inter 2000 rise 2 fall 3
```

Another user is asking for help in #145 maybe documentation for this feature needs to be improved.

**Comment by Sikian** [comment]
@fabn I believe the `ADDITIONAL_BACKEND` needs a frontend to work with, but I may be wrong with this. As I did this some months ago, I'm no longer sure the details of why I went my way around that settings.

**Pull request closed without merging**
