### PR TITLE
Provide a smaller image (37 MB) based on Alpine Linux

### PR DESCRIPTION
**Pull request by blueimp**
This is an alternative image based on Alpine Linux.
I propose to provide it via an additional tag for folks who value small image sizes.

The image size reported by `docker images` is only `37 MB` compared to the `234 MB` of the official image.

The list of changes compared to `master`:

* Use `alpine:edge` as base image.
* Use `tini` as entrypoint.
* Install the `dockercloud-haproxy` python package via GitHub url.
* Clean up obsolete installation files.
* Fix missing `${DOCKER_HOST_IP}` in the integration tests.
* Add `.dockerignore` file.

The tests ran successfully; I used the following command to run them:

```sh
docker run --rm -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$PWD:$PWD" \
  -w "$PWD" \
  -e DOCKER_HOST_IP=$(docker-machine ip) \
  blueimp/dind:1.9 \
  sh -c 'pip install websocket-client==0.32.0 six==1.9.0 && exec ./test.sh'
```

I've also set up an automated build of this alternative image on [Docker Hub](https://hub.docker.com/r/blueimp/dockercloud-haproxy) that you can try out with the following `docker-compose.yml`:

```yml
version: '2'
services:
  web:
    image: dockercloud/hello-world
  lb:
    image: blueimp/dockercloud-haproxy:1.2
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
```

 Thanks for your consideration.

### CODE REVIEW

**Comment by tifayuki** [comment]
Hello @blueimp 
It is great to move the base image from ubuntu to alpine.

Can you open the PR against staging?

Also, I think it is better to keep the way that adding the source code to the image, and use `pip install .` to install the package. To install from git tags means we have to change the Docker file every time we want to modify something.

Thank you

**Comment by blueimp** [comment]
Thanks for your reply, @tifayuki.

The reason for installing the package via GitHub url is also saving image space.
If you do a `COPY` and then a `RUN` command which installs the files to a different location, this effectively doubles the size needed for the copied files, due to the way the Docker image layers are handled.

Instead of installing a specific tag, it would also be possible to install a branch, which would allow you to keep the Dockerfile as is between changes.

Or better yet, how about creating a pip package out of this project and upload it to the pip package index?

**Comment by tifayuki** [comment]
The source code is only like 370KB. It doesn't save much space, but instead, it causes troubles for dev,  CI/CD. We have to maintain different version of Dockerfile for different purpose. It doesn't worth it.

**Comment by blueimp** [comment]
In my tests, the image size increases by 11 MB, but I accept your reasoning.
I'll create an updated pull request against staging.

**Comment by blueimp** [comment]
Closing in favor of https://github.com/docker/dockercloud-haproxy/pull/13

**Pull request closed without merging**
